### ISSUE TITLE
[Triggers]: Enable adding a single-run timed trigger

### ISSUE THREAD

**Issue by AdamEr8** [AdamEr8/cibus-budget-utilizer#27]
E.g for when Thursday is not a workday.

**Comment by orgold** [comment]
This is ALMOST supported out of the box for Azure functions.
Once you add `https://portal.azure.com` to the CORS, you can manually trigger from the function's 'Code + Test' tab.

**Comment by AdamEr8** [comment]
> This is ALMOST supported out of the box for Azure functions. Once you add `https://portal.azure.com` to the CORS, you can manually trigger from the function's 'Code + Test' tab.

Yea @orgold, but it this has to be done when you need to use your credits, I want to be able to set this single-run trigger whenever I happen remember/realize I'll need one, and then forget about it

**Comment by orgold** [comment]
You refer to scheduling a one-time order in advance.
It's pretty much supported. Copy the exiting function and change function.json to trigger on specific day and month. After it triggered, you have a year to delete it if you don't want it to reoccur. Seems like a fair ROI.

**Comment by AdamEr8** [comment]
Yea, that'll work.
especially given there doesn't seem to be a "native" solution
